---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven

inputs:
  - name: conversionofunit

outputs:
  - name: resource-app

run:
  path: /bin/sh
  args: ["conversionofunit/ci/build.sh"]

